export const REVIEWS_PAGE_SIZE = 7;

export const mockReviews = [
    {
        id: "r1",
        name: "Giulia",
        role: "Onicotecnica",
        city: "Milano",
        rating: 5,
        text: "Texture bellissima, packaging curato e soprattutto risultati visibili già dalle prime applicazioni. La linea ha un aspetto molto professionale anche sul banco lavoro.",
        createdAt: "2026-02-12",
        accent: "gold",
        size: "wide",
    },
    {
        id: "r2",
        name: "Serena",
        role: "Cliente privata",
        city: "Bergamo",
        rating: 5,
        text: "Il burro emolliente mi ha sorpresa tantissimo. Piedi più morbidi senza effetto unto e profumazione elegante.",
        createdAt: "2026-02-21",
        accent: "rose",
        size: "normal",
    },
    {
        id: "r3",
        name: "Valentina",
        role: "Centro estetico",
        city: "Verona",
        rating: 5,
        text: "Prodotti facili da proporre anche alle clienti finali. La cosa che apprezzo di più è la coerenza del brand: bello, pulito e professionale.",
        createdAt: "2026-02-25",
        accent: "dark",
        size: "tall",
    },
    {
        id: "r4",
        name: "Martina",
        role: "Cliente privata",
        city: "Torino",
        rating: 4,
        text: "Spray molto piacevole e sensazione immediata di freschezza. Lo riacquisterei volentieri.",
        createdAt: "2026-02-26",
        accent: "gold",
        size: "normal",
    },
    {
        id: "r5",
        name: "Elisa",
        role: "Onicotecnica",
        city: "Padova",
        rating: 5,
        text: "Mi piace perché non sembra il solito prodotto improvvisato. Si percepisce attenzione ai dettagli sia nella formula che nella presentazione.",
        createdAt: "2026-03-01",
        accent: "rose",
        size: "normal",
    },
    {
        id: "r6",
        name: "Arianna",
        role: "Cliente privata",
        city: "Brescia",
        rating: 5,
        text: "Uso il prodotto da qualche settimana e la pelle è molto più curata. Sito semplice, ordine arrivato bene e tutto molto chiaro.",
        createdAt: "2026-03-02",
        accent: "dark",
        size: "wide",
    },
    {
        id: "r7",
        name: "Chiara",
        role: "Centro estetico",
        city: "Vicenza",
        rating: 5,
        text: "Linea molto vendibile anche visivamente. Le clienti la percepiscono subito come premium.",
        createdAt: "2026-03-03",
        accent: "gold",
        size: "normal",
    },
    {
        id: "r8",
        name: "Federica",
        role: "Cliente privata",
        city: "Monza",
        rating: 4,
        text: "Molto soddisfatta. Mi piace che i prodotti abbiano una personalità chiara e non sembrino anonimi.",
        createdAt: "2026-03-04",
        accent: "rose",
        size: "normal",
    },
    {
        id: "r9",
        name: "Alessia",
        role: "Onicotecnica",
        city: "Treviso",
        rating: 5,
        text: "Finalmente una linea che riesco a usare in cabina e a rivendere senza imbarazzo. Curata, bella e coerente.",
        createdAt: "2026-03-05",
        accent: "dark",
        size: "tall",
    },
];